[package]
name = "smackdown"
version = "0.1.0"
edition = "2024"

[dependencies]
fastrand = "2.3.0"
macroquad = "0.4.14"
# TODO: Replace the * by the latest version number.
rapier2d = { version = "*", features = [ "simd-stable" ] }
